version: "3.9"
services: 
  rabbitmq: 
    image: "rabbitmq:3-management"
    ports: 
      - "15672:15672"
      - "5672:5672"
    environment:  
      RABBITMQ_DEFAULT_USER: "host"
      RABBITMQ_DEFAULT_PASS: "host"